# Generated by Django 2.2.1 on 2020-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=11, verbose_name='商品名字')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('type', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='sun@126.com', max_length=254)),
                ('pwd', models.CharField(max_length=32)),
                ('username', models.CharField(default='', max_length=32)),
                ('phonenum', models.CharField(blank=True, max_length=11, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, '卖家'), (1, '买家')], default=1)),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0)),
                ('photo', models.ImageField(default='img/1.jpg', upload_to='img')),
                ('adress', models.TextField(default='石家庄')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
