# Generated by Django 2.2.1 on 2020-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未生成'), (1, '已生成')], default=1, verbose_name='订单状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未生成'), (1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '拒收'), (6, '已完成')], verbose_name='订单状态'),
        ),
    ]
